from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    ResourceViewSet, RequestViewSet,
    RegisterView, ProfileView, StatsView
)

# DefaultRouter auto-generates all standard CRUD URLs for ViewSets
router = DefaultRouter()
router.register(r'resources', ResourceViewSet, basename='resource')
router.register(r'requests', RequestViewSet, basename='request')

urlpatterns = [
    # ViewSet routes (auto-generated by router)
    path('', include(router.urls)),

    # Authentication
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('auth/profile/', ProfileView.as_view(), name='profile'),

    # Platform stats
    path('stats/', StatsView.as_view(), name='stats'),
]
